name: Inverugie
favicon: null
layout_spectrum: 0.51433
typography_spectrum: 0.6647743880748749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#47b658'
    - '#292929'
    - '#6b6b6b'
    - '#9d9d9d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
