name: Inverugie
favicon: null
layout_spectrum: 0.6404637144878507
typography_spectrum: 0.6647743880748749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8784171100705862
  lightness: 0.7837518351152539
  saturation: 0.02306534256786108
  rhythmicContrast: 0.9158534575253725
purpose: []
